### ISSUE TITLE
One extra point

### ISSUE THREAD

**Issue by Ma1hT3ach3r** [Noahdorego/Group-Repository#2]
When you get a high score you end up getting one extra point(it seems).
Can this be easily fixed?
What causes this?

**Comment by Noahdorego** [comment]
My score increasing system is score += 1, and when the game ends I added score -= 1 to stop it. I'll try to fix it.

**Comment by Noahdorego** [comment]
I fixed it. I was setting the high-score to score, THEN subtracting one to stop the increase.

**Comment by Ma1hT3ach3r** [comment]
Wow, I never imagined how well issues work! @Noahdorego 
You should try to post issues for other group members and see if they pick up the "ticket" and work on it.
